config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get  '/about',   to: 'static_pages#about'
  get  '/skills',   to: 'static_pages#skills'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def about
	end
	def skills
	end
	def home
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Sample Portfolio"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Skills", skills_path %></li>
      <li><%= link_to "Home", root_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "sample_app", '#', id:"logo"%>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Home", root_path%></li>
				<li><%= link_to "Skills", skills_path%></li>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>

  </head>

  <body>
  <%= render 'layouts/header' %>
    <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/about.html.erb
<div class = 'container'>
	<div class = 'row tile'>
		<div class = 'col-md-4 tile-icon'>
			<%= image_tag('me.png', :class => 'about-img center-block') %>
		</div>
		<div class = 'col-md-8 tile-body'>
			<p>My name is Leonille Christie A. Lavador. I was born on December 27th of the year 1997 and I am a current student of the University of San Carlos taking up the program of Bacherlor of Science in Informtion Technology.</p>
		</div>
	</div>
	<div class = 'row tile'>
		<div class = 'col-md-4 tile-icon'>
			<%= image_tag('cake.png', :class => 'about-img center-block') %>
		</div>
		<div class = 'col-md-8 tile-body'>
			<p>My hobbies include baking as well as eating whatever I manage to bake. I have started up a small online business in the early 2016 where I sell my baked goods and still manage it up to date.</p>
		</div>
	</div>
	<div class = 'row tile'>
		<div class = 'col-md-4 tile-icon'>
			<%= image_tag('game.png', :class => 'about-img center-block') %>
		</div>
		<div class = 'col-md-8 tile-body'>
			<p>I also enjoy playing video games like most of the people my age. My favorite games to play fall under MOBA and MMORPG.</p>
		</div>
	</div>
	<div class = 'row tile'>
		<div class = 'col-md-4 tile-icon'>
			<%= image_tag('creative.png', :class => 'about-img center-block') %>
		</div>
		<div class = 'col-md-8 tile-body'>
			<p>I took up the BSIT Program in pursuit of my aspirations to become a graphic designer and/or artist in hopes to create aesthetically pleasing applications and websites that could encourage others to take up an interest in programming as well.</p>
		</div>
	</div>
	<div class = 'row tile'>
		<div class = 'col-md-4 tile-icon'>
			<%= image_tag('cosplay.png', :class => 'about-img center-block') %>
		</div>
		<div class = 'col-md-8 tile-body'>
			<p>Another hobby of mine is cosplaying. I first cosplayed back in 2011 and I am currently still attending Cosplay and Gaming Conventions but much lesser now because of having to prioritize studies.</p>
		</div>
	</div>
	<div class = 'row tile'>
		<div class = 'col-md-4 tile-icon'>
			<%= image_tag('graduate.png', :class => 'about-img center-block') %>
		</div>
		<div class = 'col-md-8 tile-body'>
			<p>With that having been said, my current short-term goal now is to graduate on time. Being able to hold a degree for me, is a huge step to be able to reach my aspirations.</p>
		</div>
	</div>

	<div class = 'col-md-4 tile-icon'>
			<%= image_tag('contact.png', :class => 'about-img center-block') %>
		</div>
		<div class = 'col-md-8 tile-body'>
			<p>Contact me at: leonillechristie@gmail.com</p>
		</div>
</div>

app/views/static_pages/help.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Help | Ruby on rails Tutorial Sample App</title>
</head>
<body>
	<h1>Help</h1>
	<p>
		Get help on the Ruby on Rails Tutorial at the 
		<a href="http://www.railstutorial.org/help">Rails Tutroial help page</a>
		To get help on this sample app, see the 
		<a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em></a>
	</p>
</body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
	<head>
		<title>Homepage | Portfolio App</title>
	</head>
	<body>
		<h1>My Portfolio App</h1>
		<div class="center jumbotron">
			<h1>Leonille Christie A. Lavador</h1>
			<h2>
				You can contact me through:
				<p> My <a href="http://www.facebook.com/leonillechristielavador">Facebook</a> Account</p><br>
				<p> My <a href="https://github.com/leonillechristie">Github</a> Account</p><br>
				<p> My <a href="https://plus.google.com/u/0/101442678747987003985">Google</a> Account</p><br>
			</h2>
		</div>
	</body>
</html>

app/views/static_pages/skills.html.erb
<div class = 'container skill'>
	<div class = 'row'>
		<h2>Web Development Tools</h2>
		<div class = 'skillbar' data-percent = '80'>
			<span class = 'skillbar-title' style = 'background-color: #01B6AD;'>HTML</span>
			<p class = 'skillbar-bar' style = 'background-color: #01B6AD;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
		<div class = 'skillbar' data-percent = '80'>
			<span class = 'skillbar-title' style = 'background-color: #01B6AD;'>CSS</span>
			<p class = 'skillbar-bar' style = 'background-color: #0A4958;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
		<div class = 'skillbar' data-percent = '50'>
			<span class = 'skillbar-title' style = 'background-color: #01B6AD;'>JQuery</span>
			<p class = 'skillbar-bar' style = 'background-color: #0A4958;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
		<div class = 'skillbar' data-percent = '50'>
			<span class = 'skillbar-title' style = 'background-color: #01B6AD;'>PHP</span>
			<p class = 'skillbar-bar' style = 'background-color: #0A4958;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
		<div class = 'skillbar' data-percent = '60'>
			<span class = 'skillbar-title' style = 'background-color: #01B6AD;'>FireBase</span>
			<p class = 'skillbar-bar' style = 'background-color: #0A4958;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>

		<div class = 'skillbar' data-percent = '20'>
			<span class = 'skillbar-title' style = 'background-color: #01B6AD;'>Rails</span>
			<p class = 'skillbar-bar' style = 'background-color: #0A4958;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
	</div>

	<hr>

	<div class = 'row'>
		<h2>Game Development Tools</h2>
		<div class = 'skillbar' data-percent = '90'>
			<span class = 'skillbar-title' style = 'background-color: #0A4958;'>Unity</span>
			<p class = 'skillbar-bar' style = 'background-color: #FFFFFF;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
		<div class = 'skillbar' data-percent = '55'>
			<span class = 'skillbar-title' style = 'background-color: #0A4958;'>Android Studio</span>
			<p class = 'skillbar-bar' style = 'background-color: #FFFFFF;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
	</div>

	<hr>

	<div class = 'row'>
		<h2>Desktop Tools</h2>
		<div class = 'skillbar' data-percent = '80'>
			<span class = 'skillbar-title' style = 'background-color: #FFFFFF;'>Adobe Photoshop</span>
			<p class = 'skillbar-bar' style = 'background-color: #0A4958;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
		<div class = 'skillbar' data-percent = '80'>
			<span class = 'skillbar-title' style = 'background-color: #FFFFFF;'>Adobe Illustrator</span>
			<p class = 'skillbar-bar' style = 'background-color: #0A4958;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
		<div class = 'skillbar' data-percent = '80'>
			<span class = 'skillbar-title' style = 'background-color: #FFFFFF;'>Adobe Premiere</span>
			<p class = 'skillbar-bar' style = 'background-color: #0A4958;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
		<div class = 'skillbar' data-percent = '80'>
			<span class = 'skillbar-title' style = 'background-color: #FFFFFF;'>Adobe After Effects</span>
			<p class = 'skillbar-bar' style = 'background-color: #0A4958;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
	</div>
	
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>